name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check
        run: |
          echo "Rodando no runner do GitHub (ubuntu-latest)"
          echo "Listando arquivos do projeto:"
          ls -la
          # Confere se o index.html existe (só loga, não falha)
          if [ -f "index.html" ]; then
            echo "OK: index.html encontrado"
          else
            echo "AVISO: index.html NAO encontrado (verifique o nome e a pasta)"
          fi

      - name: Criar artefato (dist) sem erro
        run: |
          mkdir -p dist
          cp -r . dist/ || true

      - name: Upload de artefato
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist
